Repository leanhaja/jipangs-client, pull requests merged in 2023-02, with the labels that each got.

#2 [JIP-39] 모노레포 구성
  .eslintrc.js
  .gitignore
  README.md
  apps/native/.babel.config.js
  apps/native/.gitignore
  apps/native/App.tsx
  apps/native/app.json
  apps/native/assets/adaptive-icon.png
  apps/native/assets/favicon.png
  apps/native/assets/icon.png
  apps/native/assets/splash.png
  apps/native/babel.config.js
  apps/native/index.js
  apps/native/metro.config.js
  apps/native/package.json
  apps/native/tsconfig.json
  apps/web/.babel.config.js
  apps/web/.eslintrc.json
  apps/web/.gitignore
  apps/web/README.md
  apps/web/next-env.d.ts
  apps/web/next.config.js
  apps/web/package.json
  apps/web/public/favicon.ico
  apps/web/public/next.svg
  apps/web/public/thirteen.svg
  apps/web/public/vercel.svg
  apps/web/src/pages/_app.tsx
  apps/web/src/pages/_document.tsx
  apps/web/src/pages/index.tsx
  apps/web/src/styles/globals.css
  apps/web/src/styles/index.module.css
  apps/web/tsconfig.json
  package.json
  packages/eslint-config-custom/index.js
  packages/eslint-config-custom/package.json
  packages/tsconfig/README.md
  packages/tsconfig/base.json
  packages/tsconfig/nextjs.json
  packages/tsconfig/package.json
  packages/tsconfig/react-library.json
  packages/ui/dist/index.d.ts
  packages/ui/dist/index.js
  packages/ui/dist/index.mjs
  packages/ui/package.json
  packages/ui/src/button/index.tsx
  packages/ui/src/button/styled.ts
  packages/ui/src/index.tsx
  packages/ui/tsconfig.json
  turbo.json
  yarn.lock
Labels: Setting

#3 JIP-79-환경-구성-변경
  apps/web/.eslintrc.json
  apps/web/package.json
Labels: BugFix, Setting

#5 [JIP-88] emotion 설치
  apps/native/package.json
  apps/native/src/App.tsx
  apps/web/package.json
  apps/web/src/pages/_app.tsx
  apps/web/src/pages/index.tsx
  apps/web/src/styles/GlobalStyles.tsx
  apps/web/src/styles/globals.css
  apps/web/src/styles/index.module.css
  apps/web/src/views/home/index.tsx
  apps/web/src/views/home/styled.tsx
  packages/eslint-config-custom/index.js
  yarn.lock
Labels: BugFix, Setting

#6 JIP-93-emotion-추가-설정
  apps/web/.babel.config.js
  apps/web/package.json
  apps/web/src/styles/GlobalStyles.tsx
  apps/web/tsconfig.json
  packages/eslint-config-custom/index.js
  packages/tsconfig/base.json
  packages/tsconfig/package.json
  yarn.lock
Labels: Setting

#8 Jip 94 버튼 컴포넌트
  packages/ui/src/button/index.tsx
  packages/ui/src/button/styled.ts
  packages/ui/src/constants/color.ts
Labels: Feature, Setting

#9 Jip 95 인풋 컴포넌트
  packages/ui/src/input/generalTextInput/index.tsx
  packages/ui/src/input/generalTextInput/styles.tsx
  packages/ui/src/input/title/index.tsx
  packages/ui/src/input/title/styles.tsx
Labels: Feature

#11 feat(ui-textinputwithbutton): 버튼이 같이 있는 텍스트 인풋 컴포넌트
  packages/ui/src/input/textInputWithButton/index.tsx
  packages/ui/src/input/textInputWithButton/styles.tsx
Labels: Feature

#7 ci: web ci-cd 배포 환경 구성
  .github/workflows/deploy.yml
  appspec.yml
  deploy.sh
Labels: Deploy

#16 [JIP-98] 아이콘 컴포넌트
  apps/web/next.config.js
  apps/web/package.json
  apps/web/src/components/icon-button/index.tsx
  apps/web/src/components/icon-button/styled.tsx
  apps/web/src/components/icon/assets/before_arrow.svg
  apps/web/src/components/icon/assets/bookmark.svg
  apps/web/src/components/icon/assets/bookmark_colored.svg
  apps/web/src/components/icon/assets/check_after.svg
  apps/web/src/components/icon/assets/check_before.svg
  apps/web/src/components/icon/assets/forum.svg
  apps/web/src/components/icon/assets/home.svg
  apps/web/src/components/icon/assets/notification.svg
  apps/web/src/components/icon/assets/search.svg
  apps/web/src/components/icon/assets/share.svg
  apps/web/src/components/icon/assets/user.svg
  apps/web/src/components/icon/assets/x.svg
  apps/web/src/components/icon/index.tsx
  packages/eslint-config-custom/index.js
  yarn.lock
Labels: Feature

#18 JIP-78-디자인-시스템
  apps/web/public/fonts/Pretendard-Black.woff
  apps/web/public/fonts/Pretendard-Bold.woff
  apps/web/public/fonts/Pretendard-ExtraBold.woff
  apps/web/public/fonts/Pretendard-ExtraLight.woff
  apps/web/public/fonts/Pretendard-Light.woff
  apps/web/public/fonts/Pretendard-Medium.woff
  apps/web/public/fonts/Pretendard-Regular.woff
  apps/web/public/fonts/Pretendard-SemiBold.woff
  apps/web/public/fonts/Pretendard-Thin.woff
  apps/web/src/pages/_app.tsx
  apps/web/src/styles/GlobalStyles.tsx
  apps/web/src/styles/emotion.d.ts
  apps/web/src/styles/theme.ts
Labels: Setting

#22 JIP-100-폰트-최적화
  apps/web/src/styles/GlobalStyles.tsx
Labels: Setting

#20 JIP-41-회원정보입력-컴포넌트-프론트
  apps/web/package.json
  apps/web/src/components/user-interface/button/index.tsx
  apps/web/src/components/user-interface/button/styled.tsx
  apps/web/src/features/register/input/button-input/button/index.tsx
  apps/web/src/features/register/input/button-input/button/styled.tsx
  apps/web/src/features/register/input/button-input/index.tsx
  apps/web/src/features/register/input/button-input/styled.tsx
  apps/web/src/features/register/input/text-input/index.tsx
  apps/web/src/features/register/input/text-input/styled.tsx
  apps/web/src/features/register/title/index.tsx
  apps/web/src/features/register/title/styled.tsx
  apps/web/src/pages/register/userInfo/index.tsx
  apps/web/src/styles/GlobalStyles.tsx
  apps/web/src/styles/emotion.d.ts
  apps/web/src/styles/theme.ts
  apps/web/src/views/register/index.tsx
  apps/web/src/views/register/register.d.ts
  apps/web/src/views/register/styled.tsx
  packages/eslint-config-custom/index.js
  packages/eslint-config-custom/package.json
  packages/ui/package.json
  packages/ui/src/button/index.tsx
  packages/ui/src/button/styled.ts
  packages/ui/src/constants/color.ts
  packages/ui/src/index.tsx
  packages/ui/src/input/generalTextInput/index.tsx
  packages/ui/src/input/generalTextInput/styles.tsx
  packages/ui/src/input/selectButton/index.tsx
  packages/ui/src/input/selectButton/styles.tsx
  packages/ui/src/input/textInputWithButton/index.tsx
  packages/ui/src/input/textInputWithButton/styles.tsx
  packages/ui/src/input/title/index.tsx
  packages/ui/src/input/title/styles.tsx
  yarn.lock
Labels: Feature, Html&Css, Setting

#24 JIP-52-알림-컴포넌트-프론트
  apps/web/src/components/notice-card/index.tsx
  apps/web/src/components/notice-card/styled.tsx
Labels: Feature, Html&Css

#25 Jip 78 디자인 시스템
  apps/web/src/styles/GlobalStyles.tsx
  apps/web/src/styles/theme.ts
Labels: Setting

#26 JIP-43-모달-컴포넌트-프론트
  apps/web/public/images/logo.png
  apps/web/src/components/user-interface/button/index.tsx
  apps/web/src/components/user-interface/button/styled.tsx
  apps/web/src/features/register/complete-modal/index.tsx
  apps/web/src/features/register/complete-modal/styled.tsx
  apps/web/src/features/register/message-modal/index.tsx
  apps/web/src/features/register/message-modal/styled.tsx
  apps/web/src/hooks/useOnClickOutside.tsx
Labels: Feature, Html&Css

#28 [JIP-106] 아이콘 컴포넌트 SVG 변경
  apps/web/src/components/bottom-navigation/styled.tsx
  apps/web/src/components/card/index.tsx
  apps/web/src/components/card/styled.tsx
  apps/web/src/components/icon-button/index.tsx
  apps/web/src/components/icon-button/styled.tsx
  apps/web/src/components/icon/assets/alarm.svg
  apps/web/src/components/icon/assets/alarm_new.svg
  apps/web/src/components/icon/assets/alarm_new_inactive.svg
  apps/web/src/components/icon/assets/before_arrow.svg
  apps/web/src/components/icon/assets/bookmark.svg
  apps/web/src/components/icon/assets/bookmark_colored.svg
  apps/web/src/components/icon/assets/bookmark_filled.svg
  apps/web/src/components/icon/assets/check.svg
  apps/web/src/components/icon/assets/check_after.svg
  apps/web/src/components/icon/assets/check_before.svg
  apps/web/src/components/icon/assets/community.svg
  apps/web/src/components/icon/assets/forum.svg
  apps/web/src/components/icon/assets/home.svg
  apps/web/src/components/icon/assets/notification.svg
  apps/web/src/components/icon/assets/user.svg
  apps/web/src/components/icon/index.tsx
  apps/web/src/constants/bottom-navigation.ts
  apps/web/src/pages/alarm.tsx
  apps/web/src/pages/community.tsx
  apps/web/src/pages/forum.tsx
  apps/web/src/pages/notification.tsx
  apps/web/src/styles/emotion.d.ts
  apps/web/src/styles/theme.ts
Labels: Refactor

#32 [JIP-107] 카드 컴포넌트 수정
  apps/web/src/components/bottom-navigation/styled.tsx
  apps/web/src/components/card/index.tsx
  apps/web/src/components/card/styled.tsx
  apps/web/src/components/community-card/index.tsx
  apps/web/src/components/community-card/styled.tsx
  apps/web/src/components/icon/assets/bookmark.svg
  apps/web/src/components/icon/assets/bookmark_navigation.svg
  apps/web/src/components/icon/index.tsx
  apps/web/src/constants/bottom-navigation.ts
  apps/web/src/styles/GlobalStyles.tsx
  apps/web/src/styles/emotion.d.ts
  apps/web/src/styles/theme.ts
  packages/eslint-config-custom/index.js
  packages/ui/dist/index.d.ts
  packages/ui/dist/index.js
  packages/ui/dist/index.mjs
Labels: BugFix, Deploy, Feature, Refactor

#31 Jip 101 셀렉트 컴포넌트
  apps/web/package.json
  apps/web/src/components/bottom-navigation/styled.tsx
  apps/web/src/features/register/components/complete-modal/index.tsx
  apps/web/src/features/register/components/complete-modal/styled.tsx
  apps/web/src/features/register/components/input/button-input/button/index.tsx
  apps/web/src/features/register/components/input/button-input/button/styled.tsx
  apps/web/src/features/register/components/input/button-input/index.tsx
  apps/web/src/features/register/components/input/button-input/styled.tsx
  apps/web/src/features/register/components/input/text-input/index.tsx
  apps/web/src/features/register/components/input/text-input/styled.tsx
  apps/web/src/features/register/components/message-modal/index.tsx
  apps/web/src/features/register/components/message-modal/styled.tsx
  apps/web/src/features/register/components/select/index.tsx
  apps/web/src/features/register/components/select/styled.tsx
  apps/web/src/features/register/components/title/index.tsx
  apps/web/src/features/register/components/title/styled.tsx
  apps/web/src/styles/emotion.d.ts
  apps/web/src/styles/theme.ts
  apps/web/src/views/register/userInfo/index.tsx
  yarn.lock
Labels: Feature, Html&Css, Setting
